packages:
  - apps/*
  - packages/*
catalog:
  "@changesets/cli": ^2.29.8
  "@clerk/nextjs": ^7.3.3
  "@rollup/plugin-commonjs": 28.0.6
  "@rollup/plugin-node-resolve": 16.0.1
  "@rollup/plugin-typescript": 12.1.4
  "@prisma/client": ^7.8.0
  "@prisma/adapter-pg": ^7.8.0
  "@tailwindcss/postcss": ^4.2.1
  "@types/hast": ^3.0.4
  "@types/mdx": ^2.0.13
  "@types/node": ^25.3.2
  "@types/nprogress": ^0.2.3
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@typescript-eslint/parser": ^8.56.1
  "@windrun-huaiin/contracts": 29.0.0
  "@windrun-huaiin/backend-core": 31.0.0
  "@windrun-huaiin/base-ui": 31.0.0
  "@windrun-huaiin/lib": 31.0.0
  "@windrun-huaiin/fumadocs-local-md": 31.0.0
  "@windrun-huaiin/third-ui": 31.0.1
  "@windrun-huaiin/dev-scripts": ^31.0.0
  baseline-browser-mapping: ^2.10.0
  clsx: ^2.1.1
  dotenv: ^17.4.2
  eslint: ^9.39.1
  eslint-config-next: 16.1.6
  eslint-plugin-unused-imports: ^4.4.1
  lucide-react: ^0.577.0
  next: 16.1.6
  next-intl: ^4.8.3
  next-themes: ^0.4.6
  nprogress: ^0.2.0
  postcss: ^8.5.6
  prisma: ^7.8.0
  react: 19.2.4
  react-dom: 19.2.4
  rollup: 4.46.2
  tailwind-merge: ^3.5.0
  tailwindcss: ^4.2.1
  turbo: ^2.9.8
  typescript: ^5.8.3
  uuid: ^13.0.0
  zod: ^4.3.6
