-- 第一步：彻底删除 faq schema（连里面的表、序列、权限全炸）
-- 为防止误操作，该SQL注释掉，只有初始化时才使用！
-- DROP SCHEMA IF EXISTS faq CASCADE;

-- 第二步：重新创建干净的 faq schema
CREATE SCHEMA faq;

-- 第三步：把所有权给 postgres（防止任何权限问题）
ALTER SCHEMA faq OWNER TO postgres;

REVOKE ALL ON SCHEMA faq FROM anon, authenticated, service_role;
REVOKE ALL ON ALL TABLES IN SCHEMA faq FROM anon, authenticated, service_role;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA faq FROM anon, authenticated, service_role;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA faq FROM anon, authenticated, service_role;

REVOKE ALL ON SCHEMA faq FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA faq FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA faq FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA faq FROM PUBLIC;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_roles WHERE rolname = 'faq_app'
  ) THEN
    CREATE ROLE faq_app
      LOGIN
      PASSWORD 'XXXfaq_app';
  END IF;
END
$$;

GRANT CONNECT ON DATABASE postgres TO faq_app;
GRANT USAGE ON SCHEMA faq TO faq_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA faq TO faq_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA faq TO faq_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA faq TO faq_app;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA faq
  REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA faq
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO faq_app;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA faq
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO faq_app;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA faq
  GRANT EXECUTE ON FUNCTIONS TO faq_app;